networks:
  # The presence of these objects is sufficient to define them
  expense: {}
  # docker voulme create mysql
volumes:
  mysql:
services:
  # docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  
  backend:
    image: backend:1.0.0
    command: sh -c "sleep 10 && node /opt/backend/index.js"    # we need to use SLEEP command and start index.js so that backend is completelu UP and running #
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql
  
  frontend:
    image: frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend